### ISSUE TITLE
Quicklook plugin fails to install on Mojave

### ISSUE THREAD

**Issue by Evertt** [sveinbjornt/Phew#2]

**Comment by sveinbjornt** [comment]
I am unable to reproduce this. Does Phew report that the install failed?

**Comment by Evertt** [comment]
Yes

<img width="532" alt="screenshot 2018-10-18 at 00 05 36" src="https://user-images.githubusercontent.com/1267282/47118992-8f289280-d269-11e8-829f-14f07d33ef3a.png">

**Comment by sveinbjornt** [comment]
Does this happen both when you try to install for a single user and all users?

**Comment by Evertt** [comment]
Both

**Comment by Evertt** [comment]
Is there something I can do to give you more information? I'm also willing to give you access to my computer via teamviewer for a few minutes so you can do some debugging on my machine?

**Comment by sveinbjornt** [comment]
Are you in some sort of shared network environment e.g. at a company/university? 

Could you try doing the install again while looking at the output in Console.app?
Does it show "No plugin at path: [some path]"?

**Comment by Evertt** [comment]
Okay I don't know why, but when I did `brew cask reinstall phew` it fixed the problem.

**Comment by habere-et-dispertire** [comment]
Same problem, but on 10.13.6. Also have multiple accounts. Worked fine on Admin account, but not on Standard. Folder QuickLook did not exist on Standard account, but it didn't help creating it and reinstalling.

Manually copying FLIFImages.qlgenerator from Admin account into Standard at ~/Library/QuickLook worked.
